#- name: Install nginx
#  ansible.builtin.yum:
#     name: httpd
#     state: latest
#- name: Start Nginx
#  ansible.builtin.systemd:
#    name: nginx
#    state: started
#    enabled: yes

- name: print variable
  ansible.builtin.debug:
    msg: URL = {{ URL }}

- name: Print variable - tasks variable defined
  ansible.builtin.debug:
    msg: URL = {{ URL }}
  vars:
    URL: tasks.google.com