- name: Variable
  hosts: WEB
  vars:
    URL: google.cpm
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
## Ansible access variable with two flower brackets