
- name: Demo on conditions
  hosts: all
  connections: local
  tasks:
    - name: Print fruit name
      ansible.builtin.debug:
        msg: fruit Name - Apple

    - name: Print Vegetable Name
      ansible.builtin.debug:
        msg: Vegetable Name - Carrot